FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

# Failed since .env not found
#COPY .env ${LAMBDA_TASK_ROOT}/.env

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ARG LANGCHAIN_TRACING_V2
ENV LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}

ARG LANGCHAIN_ENDPOINT
ENV LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}

ARG LANGCHAIN_API_KEY
ENV LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}

ARG LANGCHAIN_PROJECT
ENV LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}

COPY app/ ${LAMBDA_TASK_ROOT}/app

CMD ["app.main.lambda_handler"]